apiVersion: v1
kind: Service
metadata:
  labels:
    app: rigour-customer
  name: rigour-customer
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:eu-west-1:471112616076:certificate/866c20b0-86a7-45d7-af63-3ef5d668daad"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
spec:
  ports:
  - name: http
    port: 4000
  - name: "https"
    port: 443
    targetPort: 4000
    protocol: "TCP"
  selector:
    app: rigour-customer
    tier: frontend
  sessionAffinity: None
  type: LoadBalancer
