apiVersion: v1
kind: Service
metadata:
  name: {{ include "node-app-chart.fullname" . }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "application"  # ALB type
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"  # Internet-facing ALB
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: {{ .Values.service.protocol }}
  selector:
    app: {{ include "node-app-chart.name" . }}


#apiVersion: v1
#kind: Service
#metadata:
 # name: {{ include "node-app-chart.fullname" . }}
  #labels:
   # {{- include "node-app-chart.labels" . | nindent 4 }}
#spec:
 # type: {{ .Values.service.type }}
  #ports:
   # - port: {{ .Values.service.port }}
    #  targetPort: {{ .Values.service.targetPort }}
     # protocol: {{ .Values.service.protocol }}
      #name: {{ .Values.service.name }}
  #selector:
   # {{- include "node-app-chart.selectorLabels" . | nindent 4 }}